#
# This file is part of User Dashboard.
#
# Copyright (C) 2023 GEO Secretariat.
#
# User Dashboard is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

name: manager

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  manager-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.10.0

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (GEO Knowledge Hub Manager)
        uses: docker/build-push-action@v2
        with:
          context: manager
          push: true
          file: manager/Dockerfile.prod
          build-args: |
            PUBLIC_URL=${{ env.MANAGER_PUBLIC_URL }}
          tags: geoknowledgehub/geo-dashboard-manager:${{ steps.vars.outputs.tag }}
